# Generated by Django 5.2.4 on 2025-07-26 20:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID da Instituição')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome da Instituição')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidade Federativa')),
                ('acronym', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigla')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada')),
                ('federative_unit_shield', models.ImageField(blank=True, null=True, upload_to='institutions_shields/federative_units/', verbose_name='Escudo da Unidade Federativa')),
                ('institution_shield', models.ImageField(blank=True, null=True, upload_to='institutions_shields/institutions/', verbose_name='Escudo da Instituição')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID da Unidade Organizacional')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome da Unidade')),
                ('abbreviation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Abreviação')),
                ('unit_type', models.CharField(choices=[('INSTITUTION', 'Instituição (PC, PM, GCM, etc.)'), ('HEADQUARTERS', 'Quartel General / Sede'), ('DIVISION', 'Divisão / Comando Geral'), ('DEPARTMENT', 'Departamento / Batalhão'), ('SUBDIVISION', 'Subdivisão / Companhia / Delegacia / Núcleo / Equipe'), ('SECTION', 'Seção / Setor')], max_length=50, verbose_name='Tipo de Unidade')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizational_units', to='organizations.institution', verbose_name='Instituição')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organizations.organizationalunit', verbose_name='Unidade Superior Hierárquica')),
            ],
            options={
                'verbose_name': 'Unidade Organizacional',
                'verbose_name_plural': 'Unidades Organizacionais',
                'ordering': ['name'],
            },
        ),
    ]
