# Generated by Django 5.2.4 on 2025-07-25 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome da Unidade')),
                ('unit_type', models.CharField(choices=[('INSTITUTION', 'Instituição (PC, PM, GCM, etc.)'), ('HEADQUARTERS', 'Quartel General / Sede'), ('DIVISION', 'Divisão / Comando Geral'), ('DEPARTMENT', 'Departamento / Batalhão'), ('SUBDIVISION', 'Subdivisão / Companhia / Delegacia / Núcleo / Equipe'), ('SECTION', 'Seção / Setor')], max_length=50, verbose_name='Tipo de Unidade')),
                ('abbreviation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Abreviação')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organizations.organizationalunit', verbose_name='Unidade Superior Hierárquica')),
            ],
            options={
                'verbose_name': 'Unidade Organizacional',
                'verbose_name_plural': 'Unidades Organizacionais',
                'ordering': ['name'],
            },
        ),
    ]
