# Generated by Django 5.2.4 on 2025-07-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalunit',
            name='state',
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='unit_type',
            field=models.CharField(choices=[('HEADQUARTERS', 'Quartel General / Sede'), ('DIVISION', 'Divisão / Comando Geral'), ('DEPARTMENT', 'Departamento / Batalhão'), ('SUBDIVISION', 'Subdivisão / Companhia / Delegacia / Núcleo / Equipe'), ('SECTION', 'Seção / Setor')], max_length=50, verbose_name='Tipo de Unidade'),
        ),
    ]
