# Generated by Django 5.2.4 on 2025-07-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_organizationalunit_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalunit',
            name='unit_type',
        ),
    ]
